version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - internal-network

  fastapi:
    build: ./fastapi
    # ports:
    #   - "8000:8000"
    networks:
      - internal-network

  database:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cinemate
    volumes:
      # - ./database:/var/lib/postgresql/data - Desactivado para hacer pruebas sin persistencia
      - ./database-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - internal-network

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - internal-network

networks:
  internal-network:
    driver: bridge