services:
  api-gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    networks:
      internal-network:
        ipv4_address: 10.5.0.2
  ms-user:
    build: ./user
    # ports:
    #   - "3001:3000"
    networks:
      internal-network:
        ipv4_address: 10.5.0.3
  ms-repository:
    build: ./repository
    networks:
      internal-network:
        ipv4_address: 10.5.0.4
  ms-model:
    build: ./model
    networks:
      internal-network:
        ipv4_address: 10.5.0.5
  db-data:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cinemate
    volumes:
      # - ./data-db/data:/var/lib/postgresql/data
      - ./data-db/init:/docker-entrypoint-initdb.d
    ports:
      - "8000:5432"
    networks:
      internal-network:
        ipv4_address: 10.5.0.14
  db-auth:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth
    volumes:
      - ./auth-db/data:/var/lib/postgresql/data
      - ./auth-db/init:/docker-entrypoint-initdb.d
    ports:
      - "8001:5432"
    networks:
      internal-network:
        ipv4_address: 10.5.0.15


networks:
  internal-network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1